### ISSUE TITLE
groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap$LinkedValues.head()

### ISSUE THREAD

**Issue by lukasz-raduj** [avast/docker-compose-gradle-plugin#13] opened 2016-04-01 14:23 UTC
Hey, 
I'm trying to use your plugin on TeamCity CI, but I'm getting groovy exception like this:
 

`Caused by: groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap$LinkedValues.head() is applicable for argument types: () values: []
[14:12:31][Gradle failure report] Possible solutions: clear(), clear(), max(), find(), find(), add(java.lang.Object)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp.getServiceHost(ComposeUp.groovy:108)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp$getServiceHost.callCurrent(Unknown Source)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp.createServiceInfo(ComposeUp.groovy:60)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp$_loadServicesInfo_closure4.doCall(ComposeUp.groovy:53)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp.loadServicesInfo(ComposeUp.groovy:53)
[14:12:31][Gradle failure report] 	at com.avast.gradle.dockercompose.tasks.ComposeUp.up(ComposeUp.groovy:41)
[14:12:31][Gradle failure report] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
[14:12:31][Gradle failure report] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)`

It's about this line:
https://github.com/avast/docker-compose-gradle-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L108
and seems like groovy incompatibility problem.

Versions:
docker-compose-gradle-plugin: 0.2.85
groovy: 2.4.4

**Update:**
working for:
docker-compose-gradle-plugin: 0.1.59

**Comment by Augi** [comment] 2016-04-01 14:53
Hi, thanks for the report. Unfortunately, I'm not able to reproduce this error as it's working for me with Groovy 2.4.4 :(
Which version of Gradle do you use in your project?

**Comment by fredshonorio** [comment] 2016-04-25 15:01
I was using a Gradle 2.4 wrapper and was having the same error. Upgrading to 2.11 made it work again.

**Comment by augi** [comment] 2016-04-25 15:02
I'm closing this issue as we are not able to reproduce this error with latest versions.

**Closed by augi** 2016-04-25 15:02 UTC
